### ISSUE TITLE
State license

### ISSUE THREAD

**Issue by astrojuanlu** [FOSSASystems/FOSSASAT-2#1]
Hi! Thanks a lot for sharing the source code for the software and hardware of FossaSat-2 :heart: 

However, I don't see a license in the repository, which legally means that "all rights are reserved" and all uses of this might lead to copyright infringement.

[FossaSat-1 was shared with GPL3](https://github.com/FOSSASystems/FOSSASAT-1/blob/master/LICENSE). Do you intend to use the same license for FossaSat-2?

**Comment by jgromes** [comment]
That's a very good point - thanks. Using GPLv3 now :)
