### ISSUE TITLE
Reference frames error

### ISSUE THREAD

**Issue by SergioCdV** [FOSSASystems/FOSSASAT-2#21]
In software/FossaSat2/src/ADCS/ADCS/adcs_main.cpp

https://github.com/FOSSASystems/FOSSASAT-2/blob/cfe8c75b2e419ddbf0d7e77a95fb421b0153c93a/software/FossaSat2/src/ADCS/ADCS/adcs_main.cpp#L477-L481

Solar unit panel reference frame relates to the body-ADCS frame as follows: solar X+ equals ADCS X+, solar Y+ equals body Z + and finally solar Z+ equals ADCS Y+.

[ISODRAWINGFISSASAT_2.pdf](https://github.com/FOSSASystems/FOSSASAT-2/files/4919511/ISODRAWINGFISSASAT_2.pdf)

ADCS frame is the one used for naming within the code, though it is not the one used in the dynamical model. In this sense, ADCS Z+ is renamed X+, X+ goes to Y+ and ADCS Y+ ends up as Z+.

**Comment by Gipsonek** [comment]
Ah, I forgot the IMU also doesn't follow the solar panel reference frame. So just to confirm, the correct conversion should be:

solar X+ = ADCS X+
solar Y+ = ADCS Z+
solar Z+ = ADCS Y+

**Comment by SergioCdV** [comment]
Yes, you are right

**Comment by Gipsonek** [comment]
Thank you, should be fixed in 5030998ef2a5e4d1d9dffd4de540572a26e53f45
