### ISSUE TITLE
Reference frames

### ISSUE THREAD

**Issue by SergioCdV** [FOSSASystems/FOSSASAT-2#27]
In adcs_main, lines 477-485, talking about the comments above, there's still a mistake when identifying reference frames (solar and ADCS). Solar X+ should be ADCS X+ and solar Z+ should be ADCS Y+. 

I don't know if it is just unupdated commenting or code is to be modified also. 
[
// Calculate the intensities
  // pulseLength vector follows solar panel reference frame, not ADCS frame!
  // solar X+ = ADCS Y+
  // solar Y+ = ADCS Z+
  // solar Z+ = ADCS X+
  ADCS_CALC_TYPE pulseLength[ADCS_NUM_AXES];
  pulseLength[0] = ACS_IntensitiesRectifier(adcsState.prevIntensity[0], intensity[0], adcsParams.timeStep, adcsParams.pulseAmplitude);
  pulseLength[1] = ACS_IntensitiesRectifier(adcsState.prevIntensity[2], intensity[2], adcsParams.timeStep, adcsParams.pulseAmplitude);
  pulseLength[2] = ACS_IntensitiesRectifier(adcsState.prevIntensity[1], intensity[1], adcsParams.timeStep, adcsParams.pulseAmplitude);](url)

**Comment by Gipsonek** [comment]
That's just a case of forgetting to update the comments - the actual assignments are correct, i.e.

intensity[0] -> pulseLength[0] (ADCS X+ -> solar X+)
intensity[2] -> pulseLength[1] (ADCS Z+ -> solar Y+)
intensity[1] -> pulseLength[2] (ADCS Y+ -> solar Z+)
