### ISSUE TITLE
Compiling difficulties

### ISSUE THREAD

**Issue by N6RFM** [FOSSASystems/FOSSASAT-2#32]
Hi,  

FYI, there seem to be several definition inconsistencies in the GS ino.  "Not declared in scope" observed for FREQUENCY and FSK_DATA_SHAPING.  Related compiling errors can be resolved by adjusting to definitions already in sketch to FSK_FREQUENCY, LORA_FREQUENCY and DATA_SHAPING.  FSK_CURRENT_LIMIT is also not declared in scope.  Can be resolved by editing to CURRENT_LIMIT.  

After adjustments made above, several warnings remain.  See below.  Any suggestions?  Using RadioLib 4.02.

Best to all on the team!  Looking forward to the upcoming launches.

Bob N6RFM

/home/bob/Desktop/FOSSASAT-2-master/software/GroundStation/GroundStation.ino: In function 'void cameraCapture(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t)':
/home/bob/Desktop/FOSSASAT-2-master/software/GroundStation/GroundStation.ino:940:59: warning: narrowing conversion of '(((((int)pictureSize) << 4) & 240) | ((int)(((unsigned char)((int)lightMode)) & 15)))' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
   uint8_t optData[4] = {slot, ((pictureSize << 4) & 0xF0) | (lightMode & 0x0F),
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/bob/Desktop/FOSSASAT-2-master/software/GroundStation/GroundStation.ino:941:53: warning: narrowing conversion of '(((((int)saturation) << 4) & 240) | ((int)(((unsigned char)((int)brightness)) & 15)))' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
                          ((saturation << 4) & 0xF0) | (brightness & 0x0F),
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/bob/Desktop/FOSSASAT-2-master/software/GroundStation/GroundStation.ino:942:51: warning: narrowing conversion of '(((((int)contrast) << 4) & 240) | ((int)(((unsigned char)((int)special)) & 15)))' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
                          ((contrast << 4) & 0xF0) | (special & 0x0F)};
                          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/home/bob/Desktop/FOSSASAT-2-master/software/GroundStation/GroundStation.ino: In function 'void loop()':
/home/bob/Desktop/FOSSASAT-2-master/software/GroundStation/GroundStation.ino:1275:32: warning: integer overflow in expression [-Woverflow]
         maneuver(0b00011111, 50*1000, 6000, pos);
                              ~~^~~~~

**Comment by Gipsonek** [comment]
The first three warnings are just narrowing conversions, since the camera configuration macros are implicitly defined as `int` but passed to `uint8_t` parameters. The second one is there because 50*1000 is larger than `int` range on Uno - it doesn't matter because the parameter it gets passed to is `uint32_t` type. None of the warnings will have any effect here.

**Comment by N6RFM** [comment]
Thank you for the clarification!  Much appreciated.
